In [3]:
import numpy as np




In [6]:
np.__version__

'1.20.1'

In [5]:
np.__config__.show()



blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Karthik/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Karthik/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Karthik/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Karthik/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Karthik/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Karthik/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Karthik/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Karthik/anaconda3\\Library\\include']


In [7]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
x = np.array([100,20,34])
  
print("size",x.size)
print("memory",x.itemsize)

size 3
memory 4


In [20]:
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [24]:
a= np.zeros(10)
a[4]= 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [26]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
nz= np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [28]:
a= np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
a=np.random.uniform((9,5,6))
print(a)

[8.66224626 3.90387692 2.47019001]


In [34]:
a = np.random.random((10,10))
amin, amax = a.min(), a.max()
print(amin, amax)

0.002274539078162885 0.9970095699357502


In [36]:
a = np.random.random(30)
m = a.mean()
print(a)

[0.80094996 0.08685464 0.67452904 0.11667334 0.89442202 0.02086005
 0.35128019 0.15017088 0.86649329 0.35941101 0.57043878 0.12706559
 0.92769394 0.95478585 0.14675263 0.3004458  0.51877133 0.39891924
 0.4485823  0.56492551 0.10974243 0.21692076 0.68033365 0.53792843
 0.06701056 0.17833221 0.06301227 0.66332902 0.54916927 0.88668337]


In [38]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [39]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3 ==3*0.1)

nan
False
False
nan
False


In [40]:
a = np.diag(1+np.arange(4),k =-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [42]:
a=np.zeros ((8,8), dtype=int)
a[1::2, ::2]= 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [43]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [44]:
array= np.array([[0,1], [1,0]])
a=np.tile(array,(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [45]:
a=np.random.random((5,5))
amax, amin = a.max(), a.min()
a= (a-amin)/(amax-amin)
print(a)

[[0.45500059 0.24988756 0.72152623 0.93232958 0.29568166]
 [0.24619889 0.96070079 0.40672262 0.50581293 0.76881853]
 [0.35290937 0.80281025 0.56978554 0.04801708 0.04825977]
 [0.66902722 0.91206756 0.63117897 0.0540725  0.67087698]
 [0.33585865 1.         0.23198725 0.3046844  0.        ]]


In [48]:
a= np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [50]:
ar1 = np.array([0, 1, 2, 7,9, 4])
ar2 = [1, 3, 9]
print(np.intersect1d(ar1,ar2))

[1 9]


In [51]:

today = np.datetime64('today', 'D')
print("Today: ", today)
  
yesterday = np.datetime64('today', 'D')
- np.timedelta64(1, 'D')
  
print("Yestraday: ", yesterday)
  

tomorrow = np.datetime64('today', 'D')
+ np.timedelta64(1, 'D')
  
print("Tomorrow: ", tomorrow)

Today:  2021-09-24
Yestraday:  2021-09-24
Tomorrow:  2021-09-24


In [52]:
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)
print(x)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [53]:
s = np.random.random(10)
s.sort()
print(s)

[0.11380774 0.12541016 0.32753701 0.33403735 0.54383915 0.5817404
 0.69142326 0.74746773 0.80185769 0.94318091]


In [57]:
A=np.random.randint(0,2,2)
B=np.random.randint(0,2,2)
equal=np.allclose(A,B)
print(equal)

False


In [58]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

In [59]:
a=np.random.random((10,2))
x,y = a[:,0], a[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.95017589 0.77195904 0.50304125 0.60524106 0.48520891 0.89315132
 0.85293188 0.87846508 0.43685839 1.06433633]
[0.55878688 0.7536518  0.88887755 0.95712388 1.28926427 0.86393673
 1.03103488 0.97905412 1.09780558 0.38813403]


In [60]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.33993643 0.62555194 0.         0.45394998 0.68851239 0.15621498
 0.64201057 0.22063957 0.61566507 0.26047542]


In [68]:
Z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(Z-v)).argmin()
print(Z[index])


76


In [69]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-69-3a6f5eca1821>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [72]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
print(x)

[[0.42170215 0.71404214 0.6730504  0.0588379  0.27718557 0.56881572
  0.65449383 0.04287534 0.11883497 0.19607556]
 [0.14994363 0.12794419 0.71724595 0.32339771 0.06961565 0.29419702
  0.08737668 0.56928703 0.98283068 0.51311438]
 [0.96119688 0.15492875 0.44795444 0.95216847 0.1805336  0.27365107
  0.44192472 0.15338859 0.53521416 0.47037988]
 [0.79135128 0.81595946 0.75269338 0.57827751 0.32786447 0.48071206
  0.5556657  0.83500305 0.91499564 0.50136998]
 [0.48793266 0.65973954 0.67732494 0.3929017  0.82623658 0.09508812
  0.24296716 0.63242695 0.39613568 0.79587931]]


In [73]:
s = np.random.randint(0,10,(3,3))
print(s)
print(s[s[:,1].argsort()])

[[2 1 4]
 [9 9 4]
 [8 1 3]]
[[2 1 4]
 [8 1 3]
 [9 9 4]]


In [76]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [78]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
